[WIP] Spryks cleanups
spryker-sdk/spryk pull request #66
Opened 2021-05-20 11:09 UTC by oleksandr-stoilovskyi

2021-05-20 11:55 UTC, matweew commented
@oleksandr-stoilovskyi can you check it https://github.com/spryker-sdk/spryk/pull/64?

2021-05-20 11:58 UTC, matweew commented
![image](https://user-images.githubusercontent.com/454530/118974485-8c3f3280-b97b-11eb-9f08-f7fd3e0612d8.png)

[for epic refactoring task] It would be good to rename spryks and group them by name 
AddModuleGui, AddModuleDataImport, AddModulePayment,  AddModuleYvesPage, AddModuleYvesWidget...

2021-05-20 12:01 UTC, matweew commented
@dereuromark I see your PR has `prio` label. Our epic is still in progress. Can you wait?

2021-05-20 16:07 UTC, dereuromark commented on config/spryk/spryks/Spryker/AddDefaultModule.yml
> +description: "Adds a new *module* structure with Zed(all layers stubs facades, factories), Client, Transfer skeletons."
space missing in front of (, also see others

2021-06-04 15:58 UTC, matweew reviewed
the review is not completed

2021-06-07 06:40 UTC, pushokwhite commented on src/SprykerSdk/Spryk/Model/Spryk/Command/ComposerReplaceGenerateSprykHookCommand.php
> +        }
`getFallbackMessage` was added due to this reason, so it will show the line about what should be done manually.

2021-06-07 06:55 UTC, matweew commented on src/SprykerSdk/Spryk/Model/Spryk/Command/ComposerReplaceGenerateSprykHookCommand.php
> +        }
why do we need isRunnable() always true in this case?

PS still please fix  ComposerReplaceUpdater

2021-06-07 07:31 UTC, pushokwhite commented on src/SprykerSdk/Spryk/Model/Spryk/Command/ComposerReplaceGenerateSprykHookCommand.php
> +        }
`isRunnable` is true only if we can run it for current Spryk, is not about if this command exists or not.

2021-06-07 10:28 UTC, matweew commented on src/SprykerSdk/Spryk/Model/Spryk/Command/ComposerDumpAutoloadSprykHookCommand.php
> +        return 'Please, execute `composer dump-autoload` manually.';
Please execute...

2021-06-07 11:11 UTC, pushokwhite commented on src/SprykerSdk/Spryk/Model/Spryk/Command/ComposerReplaceGenerateSprykHookCommand.php
> +        }
> please fix ComposerReplaceUpdater
https://github.com/spryker-sdk/composer-replace/pull/7

2021-06-10 10:00 UTC, matweew requested changes

2021-06-10 10:00 UTC, matweew commented on src/SprykerSdk/Spryk/Model/Spryk/Executor/SprykExecutor.php
> +    protected $commandStack;
```suggestion
    protected $sprykCommands;
```

2021-06-10 11:18 UTC, pushokwhite commented on src/SprykerSdk/Spryk/Model/Spryk/Filter/FilterFactory.php
> +            $this->createTrimBackslashFilter(),
Fixed

2021-06-10 11:20 UTC, pushokwhite commented on src/SprykerSdk/Spryk/Model/Spryk/Filter/FilterFactory.php
> +            $this->createUpperCaseFilter(),
Fixed

2021-06-10 11:22 UTC, pushokwhite commented on src/SprykerSdk/Spryk/Model/Spryk/Filter/FilterFactory.php
> +            $this->createUpperCaseFirstFilter(),
Fixed

2021-06-10 11:23 UTC, pushokwhite commented on src/SprykerSdk/Spryk/Model/Spryk/Filter/FilterFactory.php
> +            $this->createLowerCaseFilter(),
Fixed

2021-06-10 11:25 UTC, pushokwhite commented on src/SprykerSdk/Spryk/Model/Spryk/Filter/FilterFactory.php
>              $this->createCamelBackFilter(),
I see only one.

2021-06-10 11:27 UTC, pushokwhite commented on src/SprykerSdk/Spryk/Model/Spryk/Filter/FilterFactory.php
>              $this->createCamelBackFilter(),
Removed

2021-06-10 11:30 UTC, pushokwhite commented on src/SprykerSdk/Spryk/Model/Spryk/Filter/FilterFactory.php
> +            $this->createArgumentToDocParameterFilter(),
That was painful

2021-06-10 11:31 UTC, pushokwhite commented on src/SprykerSdk/Spryk/Model/Spryk/Filter/RemoveWidgetSuffixFilter.php
> +    public const WIDGET_SUFFIX = 'Widget';
Fixed

2021-06-10 11:36 UTC, pushokwhite commented on src/SprykerSdk/Spryk/Model/Spryk/Filter/RemoveWidgetSuffixFilter.php
> +        return ucfirst($value);
> why not just {{ widget }}?
Argument widget can be passed like `NewSmthDoingWidget` or `NewSmthDoing`, both are valid.
> but probably could be replaced with widget | replace('Widget', '');
Argument can be Ne`wIdGet`SomethingWidget .
Just a guess, but I'd leave this as it is.

2021-06-11 05:12 UTC, pushokwhite commented on src/SprykerSdk/Spryk/Model/Spryk/Executor/SprykExecutor.php
> +    protected $commandStack;
Fixed

2021-06-11 05:13 UTC, pushokwhite commented on config/spryk/templates/coveralls.yml.twig
> +service_name: travis-ci
Removed

2021-06-11 05:14 UTC, pushokwhite commented on src/SprykerSdk/Spryk/Model/Spryk/Filter/ArgumentToDocParameterFilter.php
> +class ArgumentToDocParameterFilter implements FilterInterface
Added

2021-06-11 06:13 UTC, pushokwhite commented on src/SprykerSdk/Spryk/Model/Spryk/Filter/CamelCaseToDashFilter.php
> +class CamelCaseToDashFilter implements FilterInterface
Fixed

2021-06-11 06:14 UTC, pushokwhite commented on src/SprykerSdk/Spryk/Model/Spryk/Definition/SprykDefinition.php
> +        return $this;
You have fixed

2021-06-11 06:15 UTC, pushokwhite commented on src/SprykerSdk/Spryk/Model/Spryk/Definition/Builder/SprykDefinitionBuilder.php
> +            $this->definitionCollection[$sprykDefinitionKey] = $sprykDefinition;
Done

2021-06-11 06:19 UTC, pushokwhite commented on src/SprykerSdk/Spryk/Model/Spryk/Configuration/Extender/Extenders/AbstractExtender.php
>      protected const NAME_ARGUMENT_LAYER = 'layer';
Is used now.

2021-06-11 06:20 UTC, pushokwhite commented on src/SprykerSdk/Spryk/Model/Spryk/Configuration/Extender/Extenders/AbstractExtender.php
>      protected const NAME_PLACEHOLDER_LAYER = '{{ layer }}';
Removed

2021-06-11 06:21 UTC, pushokwhite commented on config/spryk/templates/composer.json.twig
> +    },
Fixed

2021-06-11 06:22 UTC, pushokwhite commented on src/SprykerSdk/Spryk/Model/Spryk/Configuration/ConfigurationFactory.php
> +            $this->createLevelRule(),
Fixed

2021-06-11 06:25 UTC, pushokwhite commented on src/SprykerSdk/Spryk/Model/Spryk/Executor/Configuration/SprykExecutorConfiguration.php
> +        $explodedTargetModuleName = explode('.', $targetModuleName);
Fixed

2021-06-11 06:25 UTC, pushokwhite commented on src/SprykerSdk/Spryk/Model/Spryk/Executor/Configuration/SprykExecutorConfiguration.php
> +        $explodedDependentModuleName = explode('.', $dependentModuleName);
Fixed

2021-06-11 06:26 UTC, pushokwhite commented on src/SprykerSdk/Spryk/Model/Spryk/Command/AbstractSprykHookCommand.php
> +abstract class AbstractSprykHookCommand implements SprykCommandInterface
Forgot to refactor, fixed.

2021-06-11 06:29 UTC, pushokwhite commented on src/SprykerSdk/Spryk/Model/Spryk/Command/ComposerDumpAutoloadSprykHookCommand.php
> +        return 'ComposerDumpAutoload';
Left as is.

2021-06-11 06:47 UTC, pushokwhite commented on src/SprykerSdk/Spryk/Model/Spryk/Configuration/ConfigurationFactory.php
> +            $this->createLevelRule(),
`ConfigurationFactory::createConfigurationValidatorRules contains more then one new. Fix this by extract a method.`
Moved both into the separate methods.

2021-06-11 08:03 UTC, pushokwhite commented on src/SprykerSdk/Spryk/Model/Spryk/Definition/Builder/SprykDefinitionBuilder.php
> +            $this->definitionCollection[$sprykDefinitionKey] = $sprykDefinition;
We cannot, we need this in collection before we build pre/post spryks, let's leave this.

2021-06-11 08:06 UTC, pushokwhite commented on src/SprykerSdk/Spryk/Model/Spryk/Definition/Builder/SprykDefinitionBuilder.php
> +            $sprykDefinition[static::ARGUMENTS]['module'][static::ARGUMENT_KEY_VALUE] = $sprykExecutorConfiguration->getTargetModule();
Renamed to `$sprykConfiguration`.

2021-06-11 08:07 UTC, pushokwhite commented on src/SprykerSdk/Spryk/SprykConfig.php
> +    public const NAME_DEVELOPMENT_LAYER_PROJECT = 'project';
Replaced all the usage with this constants.

2021-06-11 09:46 UTC, matweew commented on src/SprykerSdk/Spryk/Model/Spryk/Definition/Builder/SprykDefinitionBuilder.php
> +            $sprykDefinition[static::ARGUMENTS]['module'][static::ARGUMENT_KEY_VALUE] = $sprykExecutorConfiguration->getTargetModule();
what about ['module']

2021-06-11 10:17 UTC, matweew commented on src/SprykerSdk/Spryk/Model/Spryk/Configuration/Extender/Extenders/ApplicationLayerExtender.php
> +//        $targetPath = $arguments['targetPath'][SprykConfig::NAME_ARGUMENT_KEY_DEFAULT];
commented code and `todo:` in this file

2021-06-11 10:25 UTC, matweew commented on src/SprykerSdk/Spryk/Model/Spryk/Filter/LowerCaseFirstFilter.php
>  class LowerCaseFirstFilter implements FilterInterface
incorrect description

2021-06-11 10:50 UTC, matweew commented on src/SprykerSdk/Spryk/Model/Spryk/Filter/CamelCaseToDashFilter.php
> + * $this->filter(`stringExample') === 'string-example';
should it be  'string-Example'?

2021-06-11 11:12 UTC, pushokwhite commented on src/SprykerSdk/Spryk/Model/Spryk/Filter/LowerCaseFirstFilter.php
>  class LowerCaseFirstFilter implements FilterInterface
Fixed

2021-06-11 11:12 UTC, pushokwhite commented on src/SprykerSdk/Spryk/Model/Spryk/Filter/CamelCaseToDashFilter.php
> + * $this->filter(`stringExample') === 'string-example';
Fixed

2021-06-11 11:14 UTC, pushokwhite commented on src/SprykerSdk/Spryk/Model/Spryk/Configuration/Extender/Extenders/ApplicationLayerExtender.php
> +//        $targetPath = $arguments['targetPath'][SprykConfig::NAME_ARGUMENT_KEY_DEFAULT];
Removed

2021-06-11 12:08 UTC, matweew approved these changes
please cleanup changelogs

2021-06-11 12:23 UTC, pushokwhite commented
> please cleanup changelogs

Done

2021-06-20 18:20 UTC, matweew approved these changes

2021-06-25 12:49 UTC, merged