APPS-3488 Added spryks creating transfers for common entity CRUD facade
spryker-sdk/spryk pull request #96
Opened 2022-03-23 16:25 UTC by miroshnikov-spryker

2022-03-24 06:50 UTC, stereomon commented on src/Spryk/Model/Spryk/Filter/PluralizeFilter.php
> +class PluralizeFilter implements FilterInterface
Perfect thing!

2022-03-24 06:50 UTC, stereomon approved these changes

2022-03-24 07:29 UTC, stereomon requested changes
One thing I missed that came to my mind now, you also need to add the new Spryks to the `postSpryk` section in the `AddCrudFacade` Spryk.

And also add some assertions to the `AddCrudFacadeTest`.

2022-03-24 11:02 UTC, miroshnikov-spryker commented on tests/_support/Module/TransferModule.php
> +        $property = $simpleXMLElement->xpath(sprintf('//transfer[@name="%s"]/property[@name="%s"]', $transferName, $propertyName))[0] ?? null;
To provide a more readable error message: "null is not a subclass of SimpleXMLElement" instead of "undefined array offset 0 at ..."

2022-03-25 07:43 UTC, stereomon approved these changes

2022-03-25 07:43 UTC, merged